Forest/Controllers/MusicAdminController.cs
using Forest.Data;
using Forest.Services.IService;
using Forest.Services.Service;
using System.Web.Mvc;

namespace Forest.Controllers
{
    public class MusicAdminController : Controller
    {
        private IMusicService _musicService;
        private IArtistService _artistService;
        private IGenreService _genreService;
        private IUserService _userService;
        public MusicAdminController()
        {
            _musicService = new MusicService();
            _artistService = new ArtistService();
            _genreService = new GenreService();
            _userService = new UserService();
        }
        [HttpGet]

        public ActionResult UpdateMusic(int id)
        {
            Music music = _musicService.GetMusic(id);
            ViewBag.Artist_ID = new SelectList(_artistService.GetArtists(), "ID", "Name", music.Artist_ID);
            ViewBag.Genre_ID = new SelectList(_genreService.GetGenres(), "ID", "Name", music.Genre_ID);
            ViewBag.User_ID = new SelectList(_userService.GetUsers(), "ID", "Name", music.User_ID);
            return View(music);
        }
        [HttpPost]
        public ActionResult UpdateMusic(int id, Music music)
        {
                //call the appropriate method of the service object, passing music object
                _musicService.UpdateMusic(music);
                //return a RedirectToAction
                //redirect to GetMusic action in MusicController, passing ID of music object
                return RedirectToAction("GetMusic", "Music", new { id = music.ID, Controller = "MusicController" });

            
        }
        // GET: MusicAdmin
        public ActionResult Index()
        {
            return View();
        }

        // GET: MusicAdmin/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: MusicAdmin/Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpGet]
        public ActionResult AddMusic()
        {
            ViewBag.Artist_ID = new SelectList(_artistService.GetArtists(), "ID", "Name");
            ViewBag.Genre_ID = new SelectList(_genreService.GetGenres(), "ID", "Name");
            ViewBag.User_ID = new SelectList(_userService.GetUsers(), "ID", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult AddMusic(Music music)
        {
            //call the appropriate method of the service object, passing music object
            _musicService.AddMusic(music);
            //return a RedirectToAction
            //redirect to GetMusic action in MusicController, passing ID of music object
            return RedirectToAction("GetMusic", "Music", new { id = music.ID, Controller = "MusicController" });
        }

        // POST: MusicAdmin/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MusicAdmin/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MusicAdmin/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: MusicAdmin/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MusicAdmin/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult DeleteMusic(int id)
        {
            return View(_musicService.GetMusic(id));
        }
        [HttpPost]
        public ActionResult DeleteMusic(int id, Music music)
        {
            Music _music = _musicService.GetMusic(id);
            //call the appropriate method of the service object, passing music object
            _musicService.DeleteMusic(_music);
            //return a RedirectToAction
            //redirect to GetMusic action in MusicController, passing ID of music object
            return RedirectToAction("GetAllMusics", "Music", new { id = music.ID, Controller = "MusicController" });
        }
    }
}

Forest/Controllers/MusicController.cs
using Forest.Data;
using Forest.Services.IService;
using Forest.Services.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forest.Controllers
{
    public class MusicController : Controller
    {
        private IMusicService _service;
        public MusicController()
        {
            _service = new MusicService();
        }
        public ActionResult GetAllMusics()
        {
            IList<Music> musiclist;
            musiclist = _service.GetAllMusics();
            return View("GetAllMusics", musiclist);
        }
        public ActionResult GetMusic(int id)
        {
            Music music;
            music = _service.GetMusic(id);
            return View("GetMusic", music);
        }
        public ActionResult GetMusics(int genreId)
        {
            IList<Music> list;
            list = _service.GetMusics(genreId);
            return View("GetMusics", list);
        }
        // GET: Music
        public ActionResult Index()
        {
            return View();
        }

        // GET: Music/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Music/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Music/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Music/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Music/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Music/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Music/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Forest/Views/Music/GetAllMusics.cshtml
@model IEnumerable<Forest.Data.Music>

@{
    ViewBag.Title = "GetAllMusics";
}

<h2>GetAllMusics</h2>

<p>
    @Html.ActionLink("Create New", "AddMusic", "MusicAdmin")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.num_track)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateReleased)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.num_track)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.duration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateReleased)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Artist.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "UpdateMusic", new { id=item.ID, Controller = "MusicAdmin" }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "DeleteMusic", new { id=item.ID, Controller = "MusicAdmin" })
        </td>
    </tr>
}

</table>

Forest/Views/Music/GetMusic.cshtml
@model Forest.Data.Music

@{
    ViewBag.Title = "GetMusic";
}

<h2>GetMusic</h2>

<div>
    <h4>Music</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.num_track)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.num_track)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.duration)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.duration)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateReleased)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateReleased)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Forest/Views/Music/GetMusics.cshtml
@model IEnumerable<Forest.Data.Music>

@{
    ViewBag.Title = "GetMusics";
}

<h2>GetMusics</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.num_track)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.duration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateReleased)
        </th>*@
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Artist.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.num_track)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.duration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateReleased)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Artist.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.Name)
        </td>
        <td>
            @Html.ActionLink("Add To Cart", "AddToCart",
                new { id = item.ID, Controller = "Cart"}) |
            @Html.ActionLink("Edit", "UpdateMusic", new { id=item.ID, Controller="MusicAdmin" }) |
            @Html.ActionLink("Details", "GetMusic", new { id=item.ID, Controller = "Music" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>