Forest/Controllers/MusicController.cs
using Forest.Data;
using Forest.Services.IService;
using Forest.Services.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Forest.Controllers
{
    public class MusicController : Controller
    {
        private IMusicService _service;
        public MusicController()
        {
            _service = new MusicService();
        }
        public ActionResult GetAllMusics()
        {
            IList<Music> musiclist;
            musiclist = _service.GetAllMusics();
            return View("GetAllMusics", musiclist);
        }
        public ActionResult GetMusic(int id)
        {
            Music music;
            music = _service.GetMusic(id);
            return View("GetMusic", music);
        }
        public ActionResult GetMusics(int genreId)
        {
            IList<Music> list;
            list = _service.GetMusics(genreId);
            return View("GetMusics", list);
        }
        // GET: Music
        public ActionResult Index()
        {
            return View();
        }

        // GET: Music/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Music/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Music/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Music/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Music/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Music/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Music/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Forest/Views/Admin/AddRole.cshtml
@{
    ViewBag.Title = "CreateRole";
}

<h2>Create Role</h2>
@Html.ActionLink("List Roles", "Index") |
@Html.ActionLink("Manage User Role", "ManageUserRoes")
<hr/>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div>Role name</div>
    <p>@Html.TextBox("RoleName")</p>
    <input type="submit" value="Save"/>
}

Forest/Views/Admin/Admin.cshtml
@{
    ViewBag.Title = "Admin";
}

<h1>Admin</h1>

<h2>Music Admin</h2>

<h3>
    @Html.ActionLink("Update Music", "GetAllMusics", "Music") |
    @Html.ActionLink("Add Music", "GetAllMusics", "Music") |
    @Html.ActionLink("Delete Music", "GetAllMusics", "Music")
</h3>

<h2>User Admin</h2>

<h3>
    @Html.ActionLink("List Users", "GetUsers", "Admin") |
    @Html.ActionLink("View Roles", "GetRoles", "Admin")
    @Html.ActionLink("View User Roles", "GetRolesforUser", "Admin") |
    @Html.ActionLink("Manage User Roles", "ManageUserRoles", "Admin")
</h3>

Forest/Views/Admin/GetRoles.cshtml
@{
    ViewBag.Title = "GetRoles";
}

<h2>List of Roles</h2>

@foreach (var role in Model)
{
    <p>
        @role.Name |
        @Html.ActionLink("Edit", "EditRole", new { Id = role.Id})|
        @Html.ActionLink("Delete", "DeleteRole", new { Id = role.Id})
    </p>
}
@Html.ActionLink("Add Role", "AddRole")

Forest/Views/Admin/GetRolesforUser.cshtml
@{
    ViewBag.Title = "GetRolesforUser";
}

<h2>Get Roles for User</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        Username : @Html.TextBox("UserName")
        <input type="submit" value="Get roles for this User" />
    </p>
}

Forest/Views/Admin/GetRolesforUserConfirmed.cshtml
@{
    ViewBag.Title = "GetRolesforUserConfirmed";
}

<h2>Roles for this user are:</h2>
@if (ViewBag.RolesforThisUser != null)
{
    <div>
        <ol>
            @foreach (string s in ViewBag.RolesforThisUser)
            {
                <li>@s</li>
            }
        </ol>
    </div>
}

Forest/Views/Admin/GetUsers.cshtml
@{
    ViewBag.Title = "GetUsers";
}

<h2>List of Users</h2>
@foreach (var user in Model)
{
    <p>
        @user.UserName |
        @Html.ActionLink("Edit", "EditUser", new { Id = user.Id}) |
        @Html.ActionLink("Delete", "DeleteUser", new { Id = user.Id})
    </p>
}
@*is this the right controller?*@
@Html.ActionLink("Add User", "Register", new { controller = "Account"})

Forest/Views/Admin/ManageUserRoles.cshtml
@{
    ViewBag.Title = "ManageUserRoles";
}

<h2>Manage User Role</h2>
@using (Html.BeginForm("ManageUserRoles", "Admin"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <p>
        User UserName: @Html.DropDownList("UserName",
                      (IEnumerable<SelectListItem>)ViewBag.Users, "Select ...")
        Role Name: @Html.DropDownList("RoleName",
        (IEnumerable<SelectListItem>)ViewBag.Roles, "Select ...")
    </p>
    <input type="submit" value="Save" />
}